version: '3.9'

services:
  frontend:
    build: 
      context: ./example-frontend
      dockerfile: Dockerfile.frontend
    ports:
      - 5000:5000

  backend:
    build:
      context: ./example-backend
      dockerfile: Dockerfile.backend
    ports:
      - 8080:8080

