version: '3.9'

services:
  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend

  frontend:
    build: 
      context: ./example-frontend
      dockerfile: Dockerfile.frontend

  backend:
    build:
      context: ./example-backend
      dockerfile: Dockerfile.backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=password
    depends_on:
      - redis
      - db

  redis:
    image: redis
    ports:
      - 6379:6379

  db:
    image: postgres:13.2-alpine
    volumes:
      - ./volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
