version: '3.9'

services:
  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend

  frontend:
    build: 
      context: ./example-frontend
      dockerfile: Dockerfile.frontend
    environment:
      - REACT_APP_BACKEND_URL=http://proxy:80

  backend:
    build:
      context: ./example-backend
      dockerfile: Dockerfile.backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=password
      - REQUEST_ORIGIN=http://proxy:80

  redis:
    image: redis

  db:
    image: postgres:15.3
    volumes:
      - ./volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
