name: Exercise3-1

on:
  push:
    branches:
      - main
    paths:
      - 'path3/Exercise3.1/express-app/**'

jobs:
  publish-docker-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: path3/Exercise3.1/express-app
          push: true
          tags: cagriyildirim/express-app:latest