name: Exercise3-1
on:
    push:
        branches:
            - main
        paths:
            - 'part3/Exercise3.1/express-app/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
      
            - name: Print message
              run: echo "There has been a change in the specified folder"